spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/GitTactician/newRepo.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

applications:
  - name: sealed-secrets
    namespace: kube-system
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  - name: cert-manager
    namespace: cert-manager
    # Inherits source from spec.source
