spec:
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

applications:
  - name: sealed-secrets
    namespace: kube-system
    sources:
      - repoURL: https://github.com/GitTactician/testValues.git
        targetRevision: main
        path: sealed-secrets
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

  - name: cert-manager
    namespace: cert-manager
    source:
      repoURL: https://github.com/GitTactician/app-of-apps.git
      targetRevision: main
      path: apps/cert-manager
    ignoreDifferences:
      - group: apps
        kind: Deployment
        jsonPointers:
          - /spec/replicas
    # Inherits source from spec.source
