spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/GitTactician/newRepo.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

applications:
  - name: sealed-secrets
    namespace: kube-system
    # metadata:
      # add argocd annotation sync wave prio 1
      # annotations:
        # argocd.argoproj.io/sync-wave: "1"
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
  
  - name: cert-manager
    namespace: cert-manager

    # No source defined here; should inherit all from global spec.source

  # - name: ingress-nginx
    # namespace: ingress-nginx
    # source:
      # repoURL: https://cbtw@dev.azure.com/cbtw/DevOps/_git/hms_aws_argocd
      # valueFiles:
        # - values.yaml
    # syncPolicy: # Application-specific syncPolicy override
      # automated:
        # prune: false
        # selfHeal: true
# 
  # - name: cert-manager
    # namespace: cert-manager
# 
  # - name: apache-httpd
    # namespace: apache-httpd
    # syncPolicy: # Application-specific syncPolicy override
      # automated:
        # prune: true
        # selfHeal: true
# 
  # - name: metrics-server
    # namespace: kube-system
    # source:
      # repoURL: https://cbtw@dev.azure.com/cbtw/DevOps/_git/hms_aws_argocd
    
  # - name: strimzi-kafka-operator
    # namespace: kafka
    # source:
      # repoURL: https://cbtw@dev.azure.com/cbtw/DevOps/_git/Strimzi
      # path: helm/strimzi
      # targetRevision: master
    # syncPolicy: # Application-specific syncPolicy override
      # automated:
        # prune: false
        # selfHeal: false
# 