apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc 
  source:
    repoURL: https://github.com/GitTactician/newRepo.git
    targetRevision: main
    path: app-of-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    
